// Content-deliverable harness: treats the deliverable as text and runs a forensics
// pass (length, structure, URLs, placeholders, internal duplication) plus per-criterion
// checks for requirement coverage, banned terms, length bounds, leftover placeholders,
// AI-disclosure, and duplicate paragraphs. Pure Node — no external services.
//
// NOTE: web-plagiarism detection (matching against the open web) needs a search API and
// is a later, dependency-gated enhancement. Internal-duplication detection here is a real
// signal that needs nothing external.
import type { CriterionResult, Evidence } from "../report.js";
import type { Check, Criterion, Deliverable, Harness, HarnessResult } from "./types.js";

const MAX_LISTED = 10;

const PLACEHOLDER_PATTERNS: Array<[string, RegExp]> = [
  ["lorem ipsum", /lorem ipsum/i],
  ["TODO/FIXME", /\b(?:TODO|FIXME|TBD|XXX)\b/],
  ["[insert …]", /\[(?:insert|your|placeholder|todo)[^\]]*\]/i],
  ["{{ mustache }}", /\{\{[^}]+\}\}/],
  ["<placeholder>", /<(?:placeholder|insert|your)[^>]*>/i],
  ["xxxx run", /x{4,}/i],
  ["your name/company here", /\byour (?:name|company|brand|text) here\b/i],
];

const AI_DISCLOSURE = /\b(?:ai[- ]generated|generated by ai|ai[- ]assisted|created with ai|made with (?:ai|artificial intelligence)|written with the help of ai)\b/i;

function words(text: string): string[] {
  return text.split(/\s+/).filter((w) => w.length > 0);
}
function paragraphs(text: string): string[] {
  return text.split(/\n\s*\n/).map((p) => p.trim()).filter((p) => p.length > 0);
}
function urls(text: string): string[] {
  return text.match(/\bhttps?:\/\/[^\s)]+/gi) ?? [];
}
function foundPlaceholders(text: string): string[] {
  return PLACEHOLDER_PATTERNS.filter(([, re]) => re.test(text)).map(([label]) => label);
}
function duplicateParagraphs(text: string): Array<{ a: number; b: number }> {
  const ps = paragraphs(text).map((p) => p.replace(/\s+/g, " ").toLowerCase());
  const seen = new Map<string, number>();
  const dups: Array<{ a: number; b: number }> = [];
  ps.forEach((p, i) => {
    if (p.length < 40) return; // ignore trivially short lines
    if (seen.has(p)) dups.push({ a: seen.get(p)! + 1, b: i + 1 });
    else seen.set(p, i);
  });
  return dups;
}

function forensics(text: string): Evidence[] {
  const w = words(text);
  const unique = new Set(w.map((x) => x.toLowerCase())).size;
  const sentences = (text.match(/[.!?]+(?:\s|$)/g) ?? []).length;
  const ph = foundPlaceholders(text);
  const dups = duplicateParagraphs(text);
  return [
    { kind: "word_count", detail: `${w.length} words`, data: w.length },
    { kind: "structure", detail: `${paragraphs(text).length} paragraph(s), ~${sentences} sentence(s)`, data: { paragraphs: paragraphs(text).length, sentences } },
    { kind: "lexical_diversity", detail: `${unique} unique words (${w.length ? Math.round((unique / w.length) * 100) : 0}%)`, data: { unique, total: w.length } },
    { kind: "urls", detail: urls(text).length ? `${urls(text).length} link(s)` : "no links", data: urls(text) },
    { kind: "placeholders", detail: ph.length ? ph.join(", ") : "none detected", data: ph },
    { kind: "internal_duplication", detail: dups.length ? `${dups.length} duplicate paragraph(s)` : "none", data: dups.slice(0, MAX_LISTED) },
  ];
}

function evaluate(text: string, check: Check): { status: "pass" | "fail"; evidence: Evidence[] } {
  const lower = text.toLowerCase();
  switch (check.kind) {
    case "must_include": {
      const mode = check.mode ?? "all";
      const present = check.phrases.filter((p) => lower.includes(p.toLowerCase()));
      const missing = check.phrases.filter((p) => !lower.includes(p.toLowerCase()));
      const ok = mode === "all" ? missing.length === 0 : present.length > 0;
      return ok
        ? { status: "pass", evidence: [{ kind: "coverage", detail: `${mode}: found ${present.length}/${check.phrases.length}`, data: present }] }
        : { status: "fail", evidence: [{ kind: "coverage_gap", detail: `${mode}: missing ${missing.join(", ")}`, data: missing }] };
    }
    case "must_not_include": {
      const hits = check.phrases.filter((p) => lower.includes(p.toLowerCase()));
      return hits.length === 0
        ? { status: "pass", evidence: [{ kind: "banned_terms", detail: "none of the banned phrases present" }] }
        : { status: "fail", evidence: [{ kind: "banned_terms_found", detail: `found: ${hits.join(", ")}`, data: hits }] };
    }
    case "min_words": {
      const n = words(text).length;
      return n >= check.min
        ? { status: "pass", evidence: [{ kind: "word_count", detail: `${n} >= ${check.min}` }] }
        : { status: "fail", evidence: [{ kind: "word_count", detail: `${n} < required ${check.min}` }] };
    }
    case "max_words": {
      const n = words(text).length;
      return n <= check.max
        ? { status: "pass", evidence: [{ kind: "word_count", detail: `${n} <= ${check.max}` }] }
        : { status: "fail", evidence: [{ kind: "word_count", detail: `${n} > allowed ${check.max}` }] };
    }
    case "no_placeholders": {
      const ph = foundPlaceholders(text);
      return ph.length === 0
        ? { status: "pass", evidence: [{ kind: "no_placeholders", detail: "no placeholder text detected" }] }
        : { status: "fail", evidence: [{ kind: "placeholders_found", detail: ph.join(", "), data: ph }] };
    }
    case "ai_disclosure_present":
      return AI_DISCLOSURE.test(text)
        ? { status: "pass", evidence: [{ kind: "ai_disclosure", detail: "disclosure phrase present" }] }
        : { status: "fail", evidence: [{ kind: "ai_disclosure_missing", detail: "no AI-disclosure phrase found" }] };
    case "no_duplicate_paragraphs": {
      const dups = duplicateParagraphs(text);
      return dups.length === 0
        ? { status: "pass", evidence: [{ kind: "no_duplicate_paragraphs", detail: "no duplicate paragraphs" }] }
        : { status: "fail", evidence: [{ kind: "duplicate_paragraphs", detail: `${dups.length} duplicate(s); first: ${JSON.stringify(dups.slice(0, 3))}`, data: dups.slice(0, MAX_LISTED) }] };
    }
    default:
      throw new Error(`'${(check as { kind: string }).kind}' is not a content check`);
  }
}

export class ContentHarness implements Harness {
  readonly type = "content";
  run(deliverable: Deliverable, criteria: Criterion[]): HarnessResult {
    const text = deliverable.content;
    return {
      forensics: forensics(text),
      results: criteria.map((c) => {
        try {
          const { status, evidence } = evaluate(text, c.check);
          return { criterionId: c.id, description: c.description, status, evidence } satisfies CriterionResult;
        } catch (e) {
          return { criterionId: c.id, description: c.description, status: "error", evidence: [{ kind: "error", detail: (e as Error).message }] } satisfies CriterionResult;
        }
      }),
    };
  }
}
